package com.baise.school.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.baise.school.data.entity.MsgEntity;

import com.baise.school.db.MsgEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig msgEntityDaoConfig;

    private final MsgEntityDao msgEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        msgEntityDaoConfig = daoConfigMap.get(MsgEntityDao.class).clone();
        msgEntityDaoConfig.initIdentityScope(type);

        msgEntityDao = new MsgEntityDao(msgEntityDaoConfig, this);

        registerDao(MsgEntity.class, msgEntityDao);
    }
    
    public void clear() {
        msgEntityDaoConfig.clearIdentityScope();
    }

    public MsgEntityDao getMsgEntityDao() {
        return msgEntityDao;
    }

}
