package com.baise.school.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.baise.school.data.entity.MsmEntity;

import com.baise.school.db.MsmEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig msmEntityDaoConfig;

    private final MsmEntityDao msmEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        msmEntityDaoConfig = daoConfigMap.get(MsmEntityDao.class).clone();
        msmEntityDaoConfig.initIdentityScope(type);

        msmEntityDao = new MsmEntityDao(msmEntityDaoConfig, this);

        registerDao(MsmEntity.class, msmEntityDao);
    }
    
    public void clear() {
        msmEntityDaoConfig.clearIdentityScope();
    }

    public MsmEntityDao getMsmEntityDao() {
        return msmEntityDao;
    }

}
